name: Train model
inputs:
- {name: preprocessed_dir, type: String}
- {name: model_output_path, type: String}
implementation:
  container:
    image: python:3.8
    command:
    - sh
    - -ec
    - |
      program_path=$(mktemp)
      printf "%s" "$0" > "$program_path"
      python3 -u "$program_path" "$@"
    - |
      def train_model(preprocessed_dir, model_output_path):
          X_train = joblib.load(f"{preprocessed_dir}/X_train.pkl")
          y_train = joblib.load(f"{preprocessed_dir}/y_train.pkl")

          model = RandomForestRegressor(n_estimators=100, random_state=42)
          model.fit(X_train, y_train)

          joblib.dump(model, model_output_path)

      import argparse
      _parser = argparse.ArgumentParser(prog='Train model', description='')
      _parser.add_argument("--preprocessed-dir", dest="preprocessed_dir", type=str, required=True, default=argparse.SUPPRESS)
      _parser.add_argument("--model-output-path", dest="model_output_path", type=str, required=True, default=argparse.SUPPRESS)
      _parsed_args = vars(_parser.parse_args())

      _outputs = train_model(**_parsed_args)
    args:
    - --preprocessed-dir
    - {inputValue: preprocessed_dir}
    - --model-output-path
    - {inputValue: model_output_path}
